dubbo:
  application:
    name: web-background
  registry:
    protocol: zookeeper
    address: 192.168.253.133:2181
server:
  port: 8080
spring:
  thymeleaf:
    cache: false
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.253.132:22122
image:
  server: http://192.168.253.132/