dubbo:
  application:
    name: user-Service
  protocol:
    port: 28804
  registry:
    protocol: zookeeper
    address: 192.168.253.133:2181
server:
  port: 9094
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
