dubbo:
  application:
    name: sso
  registry:
    protocol: zookeeper
    address: 192.168.253.133:2181
server:
  port: 8084
spring:
  thymeleaf:
    cache: false
  redis:
    host: 192.168.253.128
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 20
