dubbo:
  application:
    name: item-Service
  protocol:
    port: 28802
  registry:
    protocol: zookeeper
    address: 192.168.253.132:2181
server:
  port: 9092
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
location:
  html: D://html//
