package com.duli.entity;

import java.io.Serializable;
import java.util.Date;

public class TProduct implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.id
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.name
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.price
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.sale_price
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    private Long salePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.sale_point
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    private String salePoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.image
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.stock
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    private Long stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.flag
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    private Boolean flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.type_id
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    private Long typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.type_name
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.create_time
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.update_time
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.create_user
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    private Long createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.update_user
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    private Long updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.id
     *
     * @return the value of t_product.id
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.id
     *
     * @param id the value for t_product.id
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.name
     *
     * @return the value of t_product.name
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.name
     *
     * @param name the value for t_product.name
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.price
     *
     * @return the value of t_product.price
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.price
     *
     * @param price the value for t_product.price
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.sale_price
     *
     * @return the value of t_product.sale_price
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public Long getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.sale_price
     *
     * @param salePrice the value for t_product.sale_price
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public void setSalePrice(Long salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.sale_point
     *
     * @return the value of t_product.sale_point
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public String getSalePoint() {
        return salePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.sale_point
     *
     * @param salePoint the value for t_product.sale_point
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public void setSalePoint(String salePoint) {
        this.salePoint = salePoint == null ? null : salePoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.image
     *
     * @return the value of t_product.image
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.image
     *
     * @param image the value for t_product.image
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.stock
     *
     * @return the value of t_product.stock
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public Long getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.stock
     *
     * @param stock the value for t_product.stock
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public void setStock(Long stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.flag
     *
     * @return the value of t_product.flag
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public Boolean getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.flag
     *
     * @param flag the value for t_product.flag
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.type_id
     *
     * @return the value of t_product.type_id
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.type_id
     *
     * @param typeId the value for t_product.type_id
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.type_name
     *
     * @return the value of t_product.type_name
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.type_name
     *
     * @param typeName the value for t_product.type_name
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.create_time
     *
     * @return the value of t_product.create_time
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.create_time
     *
     * @param createTime the value for t_product.create_time
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.update_time
     *
     * @return the value of t_product.update_time
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.update_time
     *
     * @param updateTime the value for t_product.update_time
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.create_user
     *
     * @return the value of t_product.create_user
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.create_user
     *
     * @param createUser the value for t_product.create_user
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.update_user
     *
     * @return the value of t_product.update_user
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.update_user
     *
     * @param updateUser the value for t_product.update_user
     *
     * @mbg.generated Fri Aug 16 15:52:45 CST 2019
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }
}