package com.duli.entity;

import java.io.Serializable;

public class TProductDesc implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_desc.id
     *
     * @mbg.generated Tue Aug 13 15:33:36 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_desc.product_id
     *
     * @mbg.generated Tue Aug 13 15:33:36 CST 2019
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_desc.p_desc
     *
     * @mbg.generated Tue Aug 13 15:33:36 CST 2019
     */
    private String pDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_desc.id
     *
     * @return the value of t_product_desc.id
     *
     * @mbg.generated Tue Aug 13 15:33:36 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_desc.id
     *
     * @param id the value for t_product_desc.id
     *
     * @mbg.generated Tue Aug 13 15:33:36 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_desc.product_id
     *
     * @return the value of t_product_desc.product_id
     *
     * @mbg.generated Tue Aug 13 15:33:36 CST 2019
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_desc.product_id
     *
     * @param productId the value for t_product_desc.product_id
     *
     * @mbg.generated Tue Aug 13 15:33:36 CST 2019
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_desc.p_desc
     *
     * @return the value of t_product_desc.p_desc
     *
     * @mbg.generated Tue Aug 13 15:33:36 CST 2019
     */
    public String getpDesc() {
        return pDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_desc.p_desc
     *
     * @param pDesc the value for t_product_desc.p_desc
     *
     * @mbg.generated Tue Aug 13 15:33:36 CST 2019
     */
    public void setpDesc(String pDesc) {
        this.pDesc = pDesc == null ? null : pDesc.trim();
    }
}