package com.duli.entity;

import java.io.Serializable;

public class TProductType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_type.id
     *
     * @mbg.generated Tue Aug 13 16:42:31 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_type.pid
     *
     * @mbg.generated Tue Aug 13 16:42:31 CST 2019
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_type.name
     *
     * @mbg.generated Tue Aug 13 16:42:31 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_type.id
     *
     * @return the value of t_product_type.id
     *
     * @mbg.generated Tue Aug 13 16:42:31 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_type.id
     *
     * @param id the value for t_product_type.id
     *
     * @mbg.generated Tue Aug 13 16:42:31 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_type.pid
     *
     * @return the value of t_product_type.pid
     *
     * @mbg.generated Tue Aug 13 16:42:31 CST 2019
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_type.pid
     *
     * @param pid the value for t_product_type.pid
     *
     * @mbg.generated Tue Aug 13 16:42:31 CST 2019
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_type.name
     *
     * @return the value of t_product_type.name
     *
     * @mbg.generated Tue Aug 13 16:42:31 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_type.name
     *
     * @param name the value for t_product_type.name
     *
     * @mbg.generated Tue Aug 13 16:42:31 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}